language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
install:
- ./travis-tool.sh install_deps
- ./travis-tool.sh install_r microbenchmark knitr
- ./travis-tool.sh install_github robertzk/stagerunner
- ./travis-tool.sh install_r testthat
script: ./travis-tool.sh run_tests
after_failure:
- ./travis-tool.sh dump_logs
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: PKyFJGmf+W3L4tokefbWlVpidG9mvWp+EtRF6e3NrvFqnTCw2ZsQy9WwJW5OxQLShx9CpQ5MZs5L9VlI2RPzylKXE5kfYug5EkbuFAh5+wCVg+L9RpfyLncx7S6J1p+sFCYbmHBTZ7UXXdfbJYihrZMu267e7D9DI318XHBlYio=
    on_success: change
    on_failure: change
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}'
